language: java
cache:
  directories:
    - "$HOME/.gradle"
    - "$HOME/.m2/repository"
jdk:
  - openjdk8
script: mvn clean test
script: gradle clean test jar

#after_success:
#  - gradle jacocoTestReport coveralls
